sonar.projectKey=sqp_backend_project
sonar.projectName=Backend
sonar.projectVersion=1.0

# 👇 Multiple folders (OK)
sonar.sources=Backend1,Backend2,Backend3

sonar.sourceEncoding=UTF-8

# 👇 VERY IMPORTANT for Python
sonar.python.version=3

# 👇 Avoid junk folders
sonar.exclusions=**/__pycache__/**,**/*.pyc
